services:
  proof-server:
    image: "ghcr.io/midnight-ntwrk/proof-server:latest"
    container_name: "proof-server_$TESTCONTAINERS_UID"
    command: ["midnight-proof-server --network $NETWORK_ID"]
    ports:
      - "0:6300"
    environment:
      RUST_BACKTRACE: "full"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6300/version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
